# Generated by Django 3.0.2 on 2020-03-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='outstanding_fine',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
