# Generated by Django 3.0.2 on 2020-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0002_auto_20200324_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity_collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity_total',
            field=models.IntegerField(default=0),
        ),
    ]
