# Generated by Django 2.2.7 on 2020-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0002_auto_20200330_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
