# Generated by Django 3.0.2 on 2020-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0003_auto_20200324_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
