# Generated by Django 2.2.7 on 2020-04-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0003_checkout_overdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='collected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='reserved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
