# Generated by Django 3.0.2 on 2020-03-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0004_auto_20200324_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='eduline.Student'),
            preserve_default=False,
        ),
    ]
