# Generated by Django 3.0.2 on 2020-03-24 23:38

from django.db import migrations, models

import eduline.models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0005_checkout_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book.gif', upload_to=eduline.models.get_upload_path),
        ),
    ]
