# Generated by Django 2.2.7 on 2020-03-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0007_auto_20200325_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['quantity_collected', 'title']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['matric_number']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='eduline.Category'),
        ),
    ]
