# Generated by Django 2.2.7 on 2020-03-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eduline', '0008_auto_20200326_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='booked',
            new_name='reserved',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='booked_date',
        ),
        migrations.AddField(
            model_name='checkout',
            name='reserved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='collected_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
